### ISSUE TITLE
Inactive servers only

### ISSUE THREAD

**Issue by peubraw** [TS3Tools/TS3AutoDelete#1]
How can I modify this script to auto delete after the set amount of time only if the server is inactive ?

If there's no visitors or recent users using it ?

**Comment by Sebi94nbg** [comment]
Please note, that we don't support this project anymore. It's [End of Life since 12/2014](https://github.com/TS3Tools/TS3AutoDelete#end-of-life).

Anyway... You have to get the list of connected clients and check, if there are currently some online and if the last (dis-) connected client is offline for more than the set time.
